import type { BenchmarkPreset } from './types';

export const BENCHMARK_PRESETS: BenchmarkPreset[] = [
  {
    id: 'preset_university',
    name: 'University Student Enrollment',
    category: 'Academic DBMS Assignment',
    description:
      'Classic Unit 2 textbook relation containing redundant Student details, Instructor office information, and Course grades. Violates 2NF and 3NF.',
    expectedNormalForm: '1NF',
    columns: [
      { name: 'Student_ID', type: 'INT' },
      { name: 'Student_Name', type: 'VARCHAR' },
      { name: 'Student_Email', type: 'VARCHAR' },
      { name: 'Course_ID', type: 'VARCHAR' },
      { name: 'Course_Name', type: 'VARCHAR' },
      { name: 'Credits', type: 'INT' },
      { name: 'Instructor_ID', type: 'VARCHAR' },
      { name: 'Instructor_Name', type: 'VARCHAR' },
      { name: 'Instructor_Office', type: 'VARCHAR' },
      { name: 'Grade', type: 'VARCHAR' },
    ],
    fds: [
      {
        lhs: ['Student_ID'],
        rhs: ['Student_Name', 'Student_Email'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Course_ID'],
        rhs: ['Course_Name', 'Credits', 'Instructor_ID'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Instructor_ID'],
        rhs: ['Instructor_Name', 'Instructor_Office'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Student_ID', 'Course_ID'],
        rhs: ['Grade'],
        confidence: 1.0,
        isActive: true,
      },
    ],
    sampleData: [
      {
        Student_ID: 101,
        Student_Name: 'Aanya Pathak',
        Student_Email: 'aanya@univ.edu',
        Course_ID: 'CS-301',
        Course_Name: 'Database Management Systems',
        Credits: 4,
        Instructor_ID: 'INS-01',
        Instructor_Name: 'Dr. Alan Turing',
        Instructor_Office: 'Babbage Hall 402',
        Grade: 'A',
      },
      {
        Student_ID: 101,
        Student_Name: 'Aanya Pathak',
        Student_Email: 'aanya@univ.edu',
        Course_ID: 'CS-302',
        Course_Name: 'Operating Systems',
        Credits: 3,
        Instructor_ID: 'INS-02',
        Instructor_Name: 'Dr. Linus Torvalds',
        Instructor_Office: 'Turing Annex 105',
        Grade: 'A+',
      },
      {
        Student_ID: 102,
        Student_Name: 'Rohan Sharma',
        Student_Email: 'rohan@univ.edu',
        Course_ID: 'CS-301',
        Course_Name: 'Database Management Systems',
        Credits: 4,
        Instructor_ID: 'INS-01',
        Instructor_Name: 'Dr. Alan Turing',
        Instructor_Office: 'Babbage Hall 402',
        Grade: 'B+',
      },
      {
        Student_ID: 103,
        Student_Name: 'Priya Verma',
        Student_Email: 'priya@univ.edu',
        Course_ID: 'CS-303',
        Course_Name: 'Computer Networks',
        Credits: 3,
        Instructor_ID: 'INS-03',
        Instructor_Name: 'Dr. Vint Cerf',
        Instructor_Office: 'ARPA Tower 201',
        Grade: 'A',
      },
    ],
  },
  {
    id: 'preset_ecommerce',
    name: 'E-Commerce Orders & Shipping',
    category: 'Commercial Data Systems',
    description:
      'Unnormalized invoice table mixing Customer addresses, Product pricing, and Supplier locations. Contains 2NF & 3NF transitive dependencies.',
    expectedNormalForm: '1NF',
    columns: [
      { name: 'Order_ID', type: 'INT' },
      { name: 'Order_Date', type: 'DATE' },
      { name: 'Customer_ID', type: 'INT' },
      { name: 'Customer_Name', type: 'VARCHAR' },
      { name: 'Customer_ZipCode', type: 'VARCHAR' },
      { name: 'Customer_City', type: 'VARCHAR' },
      { name: 'Product_ID', type: 'VARCHAR' },
      { name: 'Product_Name', type: 'VARCHAR' },
      { name: 'Unit_Price', type: 'DECIMAL' },
      { name: 'Supplier_ID', type: 'VARCHAR' },
      { name: 'Supplier_Name', type: 'VARCHAR' },
      { name: 'Quantity', type: 'INT' },
    ],
    fds: [
      {
        lhs: ['Order_ID'],
        rhs: ['Order_Date', 'Customer_ID'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Customer_ID'],
        rhs: ['Customer_Name', 'Customer_ZipCode'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Customer_ZipCode'],
        rhs: ['Customer_City'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Product_ID'],
        rhs: ['Product_Name', 'Unit_Price', 'Supplier_ID'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Supplier_ID'],
        rhs: ['Supplier_Name'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Order_ID', 'Product_ID'],
        rhs: ['Quantity'],
        confidence: 1.0,
        isActive: true,
      },
    ],
    sampleData: [
      {
        Order_ID: 5001,
        Order_Date: '2026-08-10',
        Customer_ID: 901,
        Customer_Name: 'Rahul Mehta',
        Customer_ZipCode: '110001',
        Customer_City: 'New Delhi',
        Product_ID: 'PRD-88',
        Product_Name: 'Wireless Noise-Canceling Headphones',
        Unit_Price: 199.99,
        Supplier_ID: 'SUP-10',
        Supplier_Name: 'AudioTech Global',
        Quantity: 2,
      },
      {
        Order_ID: 5001,
        Order_Date: '2026-08-10',
        Customer_ID: 901,
        Customer_Name: 'Rahul Mehta',
        Customer_ZipCode: '110001',
        Customer_City: 'New Delhi',
        Product_ID: 'PRD-92',
        Product_Name: 'Ergonomic Mechanical Keyboard',
        Unit_Price: 149.50,
        Supplier_ID: 'SUP-12',
        Supplier_Name: 'KeyCraft Devices',
        Quantity: 1,
      },
      {
        Order_ID: 5002,
        Order_Date: '2026-08-12',
        Customer_ID: 902,
        Customer_Name: 'Sneha Patel',
        Customer_ZipCode: '400001',
        Customer_City: 'Mumbai',
        Product_ID: 'PRD-88',
        Product_Name: 'Wireless Noise-Canceling Headphones',
        Unit_Price: 199.99,
        Supplier_ID: 'SUP-10',
        Supplier_Name: 'AudioTech Global',
        Quantity: 1,
      },
    ],
  },
  {
    id: 'preset_hospital',
    name: 'Hospital Patient Appointments',
    category: 'Healthcare Information Systems',
    description:
      'Denormalized patient appointment register. Clinic room location is functionally dependent on Doctor Specialty, violating BCNF.',
    expectedNormalForm: '2NF',
    columns: [
      { name: 'Appointment_ID', type: 'INT' },
      { name: 'Patient_ID', type: 'INT' },
      { name: 'Patient_Name', type: 'VARCHAR' },
      { name: 'Patient_Phone', type: 'VARCHAR' },
      { name: 'Doctor_ID', type: 'VARCHAR' },
      { name: 'Doctor_Name', type: 'VARCHAR' },
      { name: 'Specialty', type: 'VARCHAR' },
      { name: 'Clinic_Room', type: 'VARCHAR' },
      { name: 'Appointment_Date', type: 'DATE' },
      { name: 'Diagnosis', type: 'VARCHAR' },
    ],
    fds: [
      {
        lhs: ['Appointment_ID'],
        rhs: [
          'Patient_ID',
          'Doctor_ID',
          'Appointment_Date',
          'Diagnosis',
        ],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Patient_ID'],
        rhs: ['Patient_Name', 'Patient_Phone'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Doctor_ID'],
        rhs: ['Doctor_Name', 'Specialty'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Specialty'],
        rhs: ['Clinic_Room'],
        confidence: 1.0,
        isActive: true,
      },
    ],
    sampleData: [
      {
        Appointment_ID: 8801,
        Patient_ID: 301,
        Patient_Name: 'Kavita Singh',
        Patient_Phone: '+91-9876543210',
        Doctor_ID: 'DOC-05',
        Doctor_Name: 'Dr. Sarah Jenkins',
        Specialty: 'Cardiology',
        Clinic_Room: 'Room 304 (Heart Center)',
        Appointment_Date: '2026-08-15',
        Diagnosis: 'Hypertension Checkup',
      },
      {
        Appointment_ID: 8802,
        Patient_ID: 302,
        Patient_Name: 'Amitabh Roy',
        Patient_Phone: '+91-9812345678',
        Doctor_ID: 'DOC-05',
        Doctor_Name: 'Dr. Sarah Jenkins',
        Specialty: 'Cardiology',
        Clinic_Room: 'Room 304 (Heart Center)',
        Appointment_Date: '2026-08-16',
        Diagnosis: 'ECG Review',
      },
    ],
  },
  {
    id: 'preset_library',
    name: 'Library Book Rentals',
    category: 'Public Services',
    description:
      'Single flat table recording library members, rented book titles, authors, and rental return due dates. Violates 2NF and 3NF.',
    expectedNormalForm: '1NF',
    columns: [
      { name: 'Rental_ID', type: 'INT' },
      { name: 'Member_ID', type: 'INT' },
      { name: 'Member_Name', type: 'VARCHAR' },
      { name: 'ISBN', type: 'VARCHAR' },
      { name: 'Book_Title', type: 'VARCHAR' },
      { name: 'Author_Name', type: 'VARCHAR' },
      { name: 'Publisher', type: 'VARCHAR' },
      { name: 'Rent_Date', type: 'DATE' },
      { name: 'Due_Date', type: 'DATE' },
    ],
    fds: [
      {
        lhs: ['Rental_ID'],
        rhs: ['Member_ID', 'ISBN', 'Rent_Date', 'Due_Date'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['Member_ID'],
        rhs: ['Member_Name'],
        confidence: 1.0,
        isActive: true,
      },
      {
        lhs: ['ISBN'],
        rhs: ['Book_Title', 'Author_Name', 'Publisher'],
        confidence: 1.0,
        isActive: true,
      },
    ],
    sampleData: [
      {
        Rental_ID: 1001,
        Member_ID: 44,
        Member_Name: 'Vikram Das',
        ISBN: '978-0131103627',
        Book_Title: 'The C Programming Language',
        Author_Name: 'Brian W. Kernighan, Dennis M. Ritchie',
        Publisher: 'Prentice Hall',
        Rent_Date: '2026-08-01',
        Due_Date: '2026-08-15',
      },
      {
        Rental_ID: 1002,
        Member_ID: 44,
        Member_Name: 'Vikram Das',
        ISBN: '978-0133594140',
        Book_Title: 'Database System Concepts',
        Author_Name: 'Abraham Silberschatz',
        Publisher: 'McGraw-Hill',
        Rent_Date: '2026-08-05',
        Due_Date: '2026-08-19',
      },
    ],
  },
];
